use_frameworks!

target 'RxBus-Demo-iOS' do
  platform :ios, '8.0'
  pod 'RxBus', :path => '../'

  target 'RxBus-Demo-iOS-Tests' do
    inherit! :search_paths
  end
end

target 'RxBus-Demo-macOS' do
  platform :osx, '10.10'
  pod 'RxBus', :path => '../'

  target 'RxBus-Demo-macOS-Tests' do
    inherit! :search_paths
  end
end

target 'RxBus-Demo-tvOS' do
  platform :tvos, '9.0'
  pod 'RxBus', :path => '../'

  target 'RxBus-Demo-tvOS-Tests' do
    inherit! :search_paths
  end
end
